name: sphinx

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build and gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme

      # - name: Debugging information
      #   run: |
      #     echo "github.ref:" ${{github.ref}}
      #     echo "github.event_name:" ${{github.event_name}}
      #     echo "github.head_ref:" ${{github.head_ref}}
      #     echo "github.base_ref:" ${{github.base_ref}}
      #     git rev-parse --abbrev-ref HEAD
      #     git branch
      #     git branch -a
      #     git remote -v

      - name: Sphinx build
        run: |
          make html

      - name: Debug
        run: |
          ls -l build/
